export const HOUR_HEIGHT_PX = 100
export const SLOT_HEIGHT_PX = HOUR_HEIGHT_PX / 4
export const HOURS_PER_DAY = 24
export const DAY_HEIGHT_PX = HOUR_HEIGHT_PX * HOURS_PER_DAY
export const MIN_EVENT_HEIGHT_PX = 40
export const GRIDLINES_PER_HOUR = 2
export const GRIDLINE_SPACING_PX = HOUR_HEIGHT_PX / GRIDLINES_PER_HOUR
